## Car Dheko - used car price Prediction

### Unstructured data convert into structure data


(i) Chennai cars data

In [4]:
import pandas as pd
import ast

# Load the Excel file
file_path = 'chennai_cars (2).xlsx'  # Replace with your file path
xls = pd.ExcelFile(file_path)

# Load the sheet containing unstructured data
df = pd.read_excel(file_path, sheet_name='chennai_cars.csv')

# Function to extract data from JSON-like fields
def extract_info(row):
    # Parse the JSON-like data from string
    car_detail = ast.literal_eval(row['new_car_detail'])
    car_overview = ast.literal_eval(row['new_car_overview'])
    car_feature = ast.literal_eval(row['new_car_feature'])
    car_specs = ast.literal_eval(row['new_car_specs'])

    # Extract relevant fields
    fuel_type = car_detail.get('ft')
    body_type = car_detail.get('bt')
    kilometers_driven = car_detail.get('km')
    car_model = car_detail.get('model')
    car_price = car_detail.get('price')

    registration_year = next((item['value'] for item in car_overview['top'] if item['key'] == 'Registration Year'), None)

    ownership = next((item['value'] for item in car_overview['top'] if item['key'] == 'Ownership'), None)

    features = ', '.join([f['value'] for f in car_feature['top']])

    engine_power = next((item['value'] for item in car_specs['top'] if item['key'] == 'Max Power'), None)
    mileage = next((item['value'] for item in car_specs['top'] if item['key'] == 'Mileage'), None)

    car_link = row['car_links']

    return pd.Series([fuel_type, body_type, kilometers_driven, registration_year, car_model, ownership, features, engine_power, mileage, car_price ,car_link])

# Apply the extraction function to each row in the DataFrame
df_structured_chennai = df.apply(extract_info, axis=1)

# Assign column names to the structured DataFrame
df_structured_chennai.columns = ['Fuel Type', 'Body Type', 'Kilometers Driven', 'Registration Year', 'Car Model', 'Ownership', 'Features', 'Engine Power', 'Mileage', 'Car Price','Car Link']

# Save the structured data to a new Excel file
output_path = 'structured_Chennai_cars_data.csv'
df_structured_chennai.to_csv(output_path, index=False)

print(f"Structured data saved to {output_path}")

Structured data saved to structured_Chennai_cars_data.csv

In [6]:
df_structured_chennai.head(3)

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Price,Car Link
0,Petrol,SUV,"20,000",2022,Kia Sonet,First Owner,"Power Steering, Power Windows Front, Air Condi...",118.36bhp,None,₹ 11.50 Lakh,https://www.cardekho.com/used-car-details/used...
1,Petrol,Minivans,"20,687",Feb 2015,Maruti Eeco,First Owner,"Low Fuel Warning Light, Accessory Power Outlet...",73bhp,15.37 kmpl,₹ 4.15 Lakh,https://www.cardekho.com/buy-used-car-details/...
2,Petrol,SUV,"30,000",2021,Nissan Magnite,First Owner,"Power Steering, Power Windows Front, Air Condi...",98.63bhp,20 kmpl,₹ 7.50 Lakh,https://www.cardekho.com/used-car-details/used...

(ii) Bangalore cars data

In [5]:
import pandas as pd
import ast

#Load the excel file
file_path = "bangalore_cars (2).xlsx"
xls = pd.ExcelFile(file_path)

#Load the sheet containing unstructure data
df = pd.read_excel(file_path,sheet_name= 'bangalore_cars.csv')

#Function to extract data from Json like fields
def extract_info(row):
    # Parse the Json - like data from string
    car_detail = ast.literal_eval(row['new_car_detail'])
    car_overview = ast.literal_eval(row['new_car_overview'])
    car_feature = ast.literal_eval(row['new_car_feature'])
    car_specs = ast.literal_eval(row['new_car_specs'])

    # Extract relevant fields
    fuel_type = car_detail.get('ft')
    body_type = car_detail.get('bt')
    kilometers_driven = car_detail.get('km')
    car_model = car_detail.get('model')
    car_price = car_detail.get('price')

    registration_year = next((item['value'] for item in car_overview['top'] if item['key'] == 'Registration Year'), None)

    ownership = next((item['value'] for item in car_overview['top'] if item['key'] == 'Ownership'), None)

    features = ', '.join([f['value'] for f in car_feature['top']])

    engine_power = next((item['value'] for item in car_specs['top'] if item['key'] == 'Max Power'), None)
    mileage = next((item['value'] for item in car_specs['top'] if item['key'] == 'Mileage'), None)

    car_link = row['car_links']

    return pd.Series([fuel_type, body_type, kilometers_driven, registration_year, car_model, ownership, features, engine_power, mileage,car_price ,car_link])

# Apply the extraction function to each row in the DataFrame
df_structured_bangalore = df.apply(extract_info, axis=1)

# Assign column names to the structured DataFrame
df_structured_bangalore.columns = ['Fuel Type', 'Body Type', 'Kilometers Driven', 'Registration Year', 'Car Model', 'Ownership', 'Features', 'Engine Power', 'Mileage','Car Price', 'Car Link']

# Save the structured data to a new Excel file
output_path = 'structured_Bangalore_cars_data.csv'
df_structured_bangalore.to_csv(output_path, index=False)

print(f"Structured data saved to {output_path}")

Structured data saved to structured_Bangalore_cars_data.csv

In [7]:
df_structured_bangalore.head(3)

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Price,Car Link
0,Petrol,Hatchback,"1,20,000",2015,Maruti Celerio,Third Owner,"Power Steering, Power Windows Front, Air Condi...",67.04bhp,23.1 kmpl,₹ 4 Lakh,https://www.cardekho.com/used-car-details/used...
1,Petrol,SUV,"32,706",Feb 2018,Ford Ecosport,Second Owner,"Power Steering, Power Windows Front, Air Condi...",121.31bhp,17 kmpl,₹ 8.11 Lakh,https://www.cardekho.com/buy-used-car-details/...
2,Petrol,Hatchback,"11,949",Sept 2018,Tata Tiago,First Owner,"Power Steering, Power Windows Front, Air Condi...",84bhp,23.84 kmpl,₹ 5.85 Lakh,https://www.cardekho.com/used-car-details/used...

(iii) Hyderbad cars data

In [13]:
import pandas as pd
import ast

# Load the Excel file
file_path = "hyderabad_cars (2).xlsx"  # Replace with your file path
xls = pd.ExcelFile(file_path)

# Load the sheet containing unstructured data
df = pd.read_excel(file_path, sheet_name='hyderabad_cars.csv')

# Function to extract data from JSON-like fields
def extract_info(row):
    # Parse the JSON-like data from string
    car_detail = ast.literal_eval(row['new_car_detail'])
    car_overview = ast.literal_eval(row['new_car_overview'])
    car_feature = ast.literal_eval(row['new_car_feature'])
    car_specs = ast.literal_eval(row['new_car_specs'])

    # Extract relevant fields
    fuel_type = car_detail.get('ft')
    body_type = car_detail.get('bt')
    kilometers_driven = car_detail.get('km')
    car_model = car_detail.get('model')
    car_price = car_detail.get('price')

    registration_year = next((item['value'] for item in car_overview['top'] if item['key'] == 'Registration Year'), None)

    ownership = next((item['value'] for item in car_overview['top'] if item['key'] == 'Ownership'), None)

    features = ', '.join([f['value'] for f in car_feature['top']])

    engine_power = next((item['value'] for item in car_specs['top'] if item['key'] == 'Max Power'), None)
    mileage = next((item['value'] for item in car_specs['top'] if item['key'] == 'Mileage'), None)

    car_link = row['car_links']

    return pd.Series([fuel_type, body_type, kilometers_driven, registration_year, car_model, ownership, features, engine_power, mileage,car_price ,car_link])

# Apply the extraction function to each row in the DataFrame
df_structured_hyder = df.apply(extract_info, axis=1)

# Assign column names to the structured DataFrame
df_structured_hyder.columns = ['Fuel Type', 'Body Type', 'Kilometers Driven', 'Registration Year', 'Car Model', 'Ownership', 'Features', 'Engine Power', 'Mileage', 'Car Price','Car Link']

# Save the structured data to a new Excel file
output_path = 'structured_hyderabad_cars_data.csv'
df_structured_hyder.to_csv(output_path, index=False)

print(f"Structured data saved to {output_path}")

Structured data saved to structured_hyderabad_cars_data.csv

In [14]:
df_structured_hyder.head(3)

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Price,Car Link
0,Petrol,Hatchback,"20,000",2022,Volkswagen Polo,First Owner,"Power Steering, Power Windows Front, Air Condi...",108.62bhp,16.47 kmpl,₹ 10.44 Lakh,https://www.cardekho.com/used-car-details/used...
1,Petrol,Hatchback,"85,582",Oct 2014,Hyundai EON,Second Owner,"Power Steering, Power Windows Front, Air Condi...",55.2bhp,21.1 kmpl,₹ 2.60 Lakh,https://www.cardekho.com/buy-used-car-details/...
2,Petrol,SUV,"10,000",2023,Hyundai Venue,First Owner,"Power Steering, Power Windows Front, Air Condi...",81.80bhp,None,₹ 9.55 Lakh,https://www.cardekho.com/used-car-details/used...

(iv) Delhi cars data

In [15]:
import pandas as pd
import ast

# Load the Excel file
file_path = "delhi_cars (2).xlsx"  # Replace with your file path
xls = pd.ExcelFile(file_path)

# Load the sheet containing unstructured data
df = pd.read_excel(file_path, sheet_name='delhi_cars.csv')

# Function to extract data from JSON-like fields
def extract_info(row):
    # Parse the JSON-like data from string
    car_detail = ast.literal_eval(row['new_car_detail'])
    car_overview = ast.literal_eval(row['new_car_overview'])
    car_feature = ast.literal_eval(row['new_car_feature'])
    car_specs = ast.literal_eval(row['new_car_specs'])

    # Extract relevant fields
    fuel_type = car_detail.get('ft')
    body_type = car_detail.get('bt')
    kilometers_driven = car_detail.get('km')
    car_model = car_detail.get('model')
    car_price = car_detail.get('price')

    registration_year = next((item['value'] for item in car_overview['top'] if item['key'] == 'Registration Year'), None)

    ownership = next((item['value'] for item in car_overview['top'] if item['key'] == 'Ownership'), None)

    features = ', '.join([f['value'] for f in car_feature['top']])

    engine_power = next((item['value'] for item in car_specs['top'] if item['key'] == 'Max Power'), None)
    mileage = next((item['value'] for item in car_specs['top'] if item['key'] == 'Mileage'), None)

    car_link = row['car_links']

    return pd.Series([fuel_type, body_type, kilometers_driven, registration_year, car_model, ownership, features, engine_power, mileage,car_price ,car_link])

# Apply the extraction function to each row in the DataFrame
df_structured_delhi = df.apply(extract_info, axis=1)

# Assign column names to the structured DataFrame
df_structured_delhi.columns = ['Fuel Type', 'Body Type', 'Kilometers Driven', 'Registration Year', 'Car Model', 'Ownership', 'Features', 'Engine Power', 'Mileage', 'Car Price','Car Link']

# Save the structured data to a new Excel file
output_path = 'structured_delhi_cars_data.csv'
df_structured_delhi.to_csv(output_path, index=False)

print(f"Structured data saved to {output_path}")

Structured data saved to structured_delhi_cars_data.csv

In [16]:
df_structured_delhi.head(3)

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Price,Car Link
0,Diesel,SUV,"10,000",2022,Kia Seltos,First Owner,"Power Steering, Power Windows Front, Air Condi...",113.43bhp,18 kmpl,₹ 19 Lakh,https://www.cardekho.com/used-car-details/used...
1,Petrol,SUV,"57,437",May 2016,Hyundai Creta,Second Owner,"Power Steering, Power Windows Front, Air Condi...",121.3bhp,15.29 kmpl,₹ 7.62 Lakh,https://www.cardekho.com/buy-used-car-details/...
2,Petrol,SUV,"8,000",Dec 2020,Mercedes-Benz GLC,First Owner,"Power Steering, Power Windows Front, Air Condi...",197bhp,12.74 kmpl,₹ 56 Lakh,https://www.cardekho.com/used-car-details/used...

(v) Jaipur Cars data

In [17]:
import pandas as pd
import ast

# Load the Excel file
file_path = "jaipur_cars (2).xlsx"  # Replace with your file path
xls = pd.ExcelFile(file_path)

# Load the sheet containing unstructured data
df = pd.read_excel(file_path, sheet_name='jaipur_cars.csv')

# Function to extract data from JSON-like fields
def extract_info(row):
    # Parse the JSON-like data from string
    car_detail = ast.literal_eval(row['new_car_detail'])
    car_overview = ast.literal_eval(row['new_car_overview'])
    car_feature = ast.literal_eval(row['new_car_feature'])
    car_specs = ast.literal_eval(row['new_car_specs'])

    # Extract relevant fields
    fuel_type = car_detail.get('ft')
    body_type = car_detail.get('bt')
    kilometers_driven = car_detail.get('km')
    car_model = car_detail.get('model')
    car_price = car_detail.get('price')

    registration_year = next((item['value'] for item in car_overview['top'] if item['key'] == 'Registration Year'), None)
    # car_model = next((item['value'] for item in car_overview['top'] if item['key'] == 'Car Model'), None)
    ownership = next((item['value'] for item in car_overview['top'] if item['key'] == 'Ownership'), None)

    features = ', '.join([f['value'] for f in car_feature['top']])

    engine_power = next((item['value'] for item in car_specs['top'] if item['key'] == 'Max Power'), None)
    mileage = next((item['value'] for item in car_specs['top'] if item['key'] == 'Mileage'), None)

    car_link = row['car_links']

    return pd.Series([fuel_type, body_type, kilometers_driven, registration_year, car_model, ownership, features, engine_power, mileage,car_price ,car_link])

# Apply the extraction function to each row in the DataFrame
df_structured_jai = df.apply(extract_info, axis=1)

# Assign column names to the structured DataFrame
df_structured_jai.columns = ['Fuel Type', 'Body Type', 'Kilometers Driven', 'Registration Year', 'Car Model', 'Ownership', 'Features', 'Engine Power', 'Mileage','Car Price' ,'Car Link']

# Save the structured data to a new Excel file
output_path = 'structured_jaipur_cars_data.csv'
df_structured_jai.to_csv(output_path, index=False)

print(f"Structured data saved to {output_path}")

Structured data saved to structured_jaipur_cars_data.csv

In [18]:
df_structured_jai.head(3)

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Price,Car Link
0,Diesel,Hatchback,"1,20,000",2015,Hyundai i20,Second Owner,"Power Steering, Power Windows Front, Air Condi...",88.73bhp,22.54 kmpl,₹ 5.10 Lakh,https://www.cardekho.com/used-car-details/used...
1,Petrol,Hatchback,"66,951",Jan 2012,Maruti Swift,First Owner,"Power Steering, Power Windows Front, Air Condi...",88.50bhp,22.38 kmpl,₹ 3.81 Lakh,https://www.cardekho.com/buy-used-car-details/...
2,Petrol,Hatchback,"80,000",2016,Maruti Celerio,Second Owner,"Power Steering, Power Windows Front, Air Condi...",67.04bhp,23.1 kmpl,₹ 3.20 Lakh,https://www.cardekho.com/used-car-details/used...

(vi) Kolkata Cars data

In [19]:
import pandas as pd
import ast

# Load the Excel file
file_path ="kolkata_cars (2).xlsx"  # Replace with your file path
xls = pd.ExcelFile(file_path)

# Load the sheet containing unstructured data
df = pd.read_excel(file_path, sheet_name='kolkata_cars.csv')

# Function to extract data from JSON-like fields
def extract_info(row):
    # Parse the JSON-like data from string
    car_detail = ast.literal_eval(row['new_car_detail'])
    car_overview = ast.literal_eval(row['new_car_overview'])
    car_feature = ast.literal_eval(row['new_car_feature'])
    car_specs = ast.literal_eval(row['new_car_specs'])

    # Extract relevant fields
    fuel_type = car_detail.get('ft')
    body_type = car_detail.get('bt')
    kilometers_driven = car_detail.get('km')
    car_model = car_detail.get('model')
    car_price = car_detail.get('price')

    registration_year = next((item['value'] for item in car_overview['top'] if item['key'] == 'Registration Year'), None)
    #car_model = next((item['value'] for item in car_overview['top'] if item['key'] == 'Car Model'), None)
    ownership = next((item['value'] for item in car_overview['top'] if item['key'] == 'Ownership'), None)

    features = ', '.join([f['value'] for f in car_feature['top']])

    engine_power = next((item['value'] for item in car_specs['top'] if item['key'] == 'Max Power'), None)
    mileage = next((item['value'] for item in car_specs['top'] if item['key'] == 'Mileage'), None)

    car_link = row['car_links']

    return pd.Series([fuel_type, body_type, kilometers_driven, registration_year, car_model, ownership, features, engine_power, mileage,car_price,car_link])

# Apply the extraction function to each row in the DataFrame
df_structured_kolkata = df.apply(extract_info, axis=1)

# Assign column names to the structured DataFrame
df_structured_kolkata.columns = ['Fuel Type', 'Body Type', 'Kilometers Driven', 'Registration Year', 'Car Model', 'Ownership', 'Features', 'Engine Power', 'Mileage','Car Price' ,'Car Link']

# Save the structured data to a new Excel file
output_path = 'structured_kolkata_cars_data.csv'
df_structured_kolkata.to_csv(output_path, index=False)

print(f"Structured data saved to {output_path}")

Structured data saved to structured_kolkata_cars_data.csv

In [20]:
df_structured_kolkata.head(3)

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Price,Car Link
0,Petrol,Sedan,"70,000",2014,Toyota Camry,Third Owner,"Power Steering, Power Windows Front, Air Condi...",158.2bhp,19.16 kmpl,₹ 9.75 Lakh,https://www.cardekho.com/used-car-details/used...
1,Petrol,Hatchback,"23,981",Jul 2017,Datsun RediGO,First Owner,"Power Steering, Power Windows Front, Air Condi...",53.64bhp,22.7 kmpl,₹ 2.66 Lakh,https://www.cardekho.com/buy-used-car-details/...
2,Petrol,SUV,"7,100",Nov 2021,Renault Kiger,First Owner,"Power Steering, Power Windows Front, Air Condi...",71.01bhp,19.03 kmpl,₹ 5.95 Lakh,https://www.cardekho.com/used-car-details/used...

### Merge all cars data

In [23]:
import pandas as pd

chennai_df = pd.read_csv('structured_Chennai_cars_data.csv')
bangalore_df = pd.read_csv('structured_Bangalore_cars_data.csv')
hyderabad_df = pd.read_csv('structured_hyderabad_cars_data.csv')
delhi_df = pd.read_csv('structured_delhi_cars_data.csv')
kolkata_df = pd.read_csv('structured_kolkata_cars_data.csv')

# Add a new column 'City' and assign the value to all rows

chennai_df['City'] = 'Chennai'
bangalore_df['City'] = 'Bangalore'
delhi_df['City'] = 'Delhi'
hyderabad_df['City'] = 'Hyderabad'
kolkata_df['City'] = 'Kolkata'


# Concatenate all datasets into a single dataset
combined_df = pd.concat([chennai_df,bangalore_df,delhi_df,hyderabad_df,kolkata_df])

# Save the combined dataset to a new CSV file
combined_df.to_csv('cars_details.csv', index=False)

print("Combined dataset saved to 'cars_details.csv'")

Combined dataset saved to 'cars_details.csv'

In [24]:
df = pd.read_csv("cars_details.csv",low_memory= False)
df.head(3)

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Price,Car Link,City
0,Petrol,SUV,"20,000",2022,Kia Sonet,First Owner,"Power Steering, Power Windows Front, Air Condi...",118.36bhp,NaN,₹ 11.50 Lakh,https://www.cardekho.com/used-car-details/used...,Chennai
1,Petrol,Minivans,"20,687",Feb 2015,Maruti Eeco,First Owner,"Low Fuel Warning Light, Accessory Power Outlet...",73bhp,15.37 kmpl,₹ 4.15 Lakh,https://www.cardekho.com/buy-used-car-details/...,Chennai
2,Petrol,SUV,"30,000",2021,Nissan Magnite,First Owner,"Power Steering, Power Windows Front, Air Condi...",98.63bhp,20 kmpl,₹ 7.50 Lakh,https://www.cardekho.com/used-car-details/used...,Chennai